import { MegaMenuType } from "../(layout)/header/types";
import { LiaLaptopSolid, LiaPencilRulerSolid } from "react-icons/lia";
import { BsPhone } from "react-icons/bs";

export const MockMegaMenu: MegaMenuType = [
  {
    id: 1,
    category: "MOBILE",
    icon: <BsPhone className='text-xl text-[#3f4064]' />,
    title: "موبایل",
    data: [
      {
        id: 11,
        title: "برندهای مختلف گوشی موبایل",
        list: [
          { id: 111, title: "گوشی آیفون" },
          { id: 112, title: "گوشی سامسونگ" },
          { id: 113, title: "گوشی شیائومی" },
          { id: 114, title: "گوشی نوکیا" },
          { id: 115, title: "گوشی آیفون" },
          { id: 116, title: "گوشی سامسونگ" },
          { id: 117, title: "گوشی شیائومی" },
          { id: 118, title: "گوشی نوکیا" },
          { id: 119, title: "گوشی آیفون" },
          { id: 120, title: "گوشی سامسونگ" },
          { id: 121, title: "گوشی شیائومی" },
          { id: 122, title: "گوشی نوکیا" },
        ],
      },
      {
        id: 12,
        title: "گوشی براساس قیمت",
        list: [
          { id: 123, title: "گوشی ارزان" },
          { id: 124, title: "گوشی گران" },
          { id: 125, title: "گوشی قسطی" },
          { id: 126, title: "گوشی تا 7 میلیون تومان" },
          { id: 127, title: "گوشی تا 8 میلیون تومان" },
          { id: 128, title: "گوشی تا 9 میلیون تومان" },
        ],
      },
      {
        id: 13,
        title: "گوشی براساس عملکرد",
        list: [
          { id: 13, title: "گوشی 1" },
          { id: 13, title: "گوشی 2" },
          { id: 13, title: "گوشی 3" },
          { id: 13, title: "گوشی 4" },
          { id: 13, title: "گوشی 5" },
          { id: 13, title: "گوشی 6" },
        ],
      },
      {
        id: 14,
        title: "تبلت",
        list: [
          { id: 141, title: "تبلت 1" },
          { id: 142, title: "تبلت 1" },
          { id: 143, title: "تبلت 1" },
          { id: 144, title: "تبلت 1" },
          { id: 145, title: "تبلت 1" },
          { id: 146, title: "تبلت 1" },
          { id: 147, title: "تبلت 1" },
          { id: 148, title: "تبلت 1" },
          { id: 149, title: "تبلت 1" },
        ],
      },
      {
        id: 11,
        title: "برندهای مختلف گوشی موبایل",
        list: [
          { id: 111, title: "گوشی آیفون" },
          { id: 112, title: "گوشی سامسونگ" },
          { id: 113, title: "گوشی شیائومی" },
          { id: 114, title: "گوشی نوکیا" },
          { id: 115, title: "گوشی آیفون" },
          { id: 116, title: "گوشی سامسونگ" },
          { id: 117, title: "گوشی شیائومی" },
          { id: 118, title: "گوشی نوکیا" },
          { id: 119, title: "گوشی آیفون" },
          { id: 120, title: "گوشی سامسونگ" },
          { id: 121, title: "گوشی شیائومی" },
          { id: 122, title: "گوشی نوکیا" },
        ],
      },
      {
        id: 12,
        title: "گوشی براساس قیمت",
        list: [
          { id: 123, title: "گوشی ارزان" },
          { id: 124, title: "گوشی گران" },
          { id: 125, title: "گوشی قسطی" },
          { id: 126, title: "گوشی تا 7 میلیون تومان" },
          { id: 127, title: "گوشی تا 8 میلیون تومان" },
          { id: 128, title: "گوشی تا 9 میلیون تومان" },
        ],
      },
      {
        id: 13,
        title: "گوشی براساس عملکرد",
        list: [
          { id: 13, title: "گوشی 1" },
          { id: 13, title: "گوشی 2" },
          { id: 13, title: "گوشی 3" },
          { id: 13, title: "گوشی 4" },
          { id: 13, title: "گوشی 5" },
          { id: 13, title: "گوشی 6" },
        ],
      },
      {
        id: 14,
        title: "تبلت",
        list: [
          { id: 141, title: "تبلت 1" },
          { id: 142, title: "تبلت 1" },
          { id: 143, title: "تبلت 1" },
          { id: 144, title: "تبلت 1" },
          { id: 145, title: "تبلت 1" },
          { id: 146, title: "تبلت 1" },
          { id: 147, title: "تبلت 1" },
          { id: 148, title: "تبلت 1" },
          { id: 149, title: "تبلت 1" },
        ],
      },
    ],
  },
  {
    id: 2,
    category: "DIGITAL",
    icon: <LiaLaptopSolid className='text-xl text-[#3f4064]' />,
    title: "کالای دیجیتال",
    data: [
      {
        id: 22,
        title: "لپ تاپ",
        list: [
          { id: 221, title: "لپ تاپ 1" },
          { id: 222, title: "لپ تاپ 1" },
          { id: 223, title: "لپ تاپ 1" },
          { id: 224, title: "لپ تاپ 1" },
          { id: 225, title: "لپ تاپ 1" },
        ],
      },
      {
        id: 23,
        title: "هدفون",
        list: [
          { id: 231, title: "هدفون 1" },
          { id: 232, title: "هدفون 1" },
          { id: 233, title: "هدفون 1" },
          { id: 234, title: "هدفون 1" },
          { id: 235, title: "هدفون 1" },
        ],
      },
    ],
  },
  {
    id: 3,
    category: "ART",
    icon: <LiaPencilRulerSolid className='text-xl text-[#3f4064]' />,
    title: "کتاب، لوازم تحریر و هنر",
    data: [
      {
        id: 33,
        title: "لوازم تحریر",
        list: [
          { id: 331, title: "لوازم تحریر" },
          { id: 332, title: "لوازم تحریر" },
          { id: 333, title: "لوازم تحریر" },
          { id: 334, title: "لوازم تحریر" },
        ],
      },
    ],
  },
];
