export const ShopingCardData = {
  count: 15,
  list: [
    {
      id: 0,
      title: "",
    },
  ],
};

export const cart = {
  status: 200,
  data: {
    is_logged_in: true,
    digiclub: {
      is_digiclub_activated: true,
      points: 11,
      reward_url_threshold: 50,
      claimable_points: 0,
    },
    digiplus: {
      subscription_remaining_days: null,
      is_activated: false,
      user_state: "lead",
      is_general_location_jet_eligible: false,
    },
    notification: {
      notification: {
        count: 26,
      },
    },
    user: {
      id: 73559674,
      first_name: "محمد",
      last_name: "گل محمدی",
      phone: "",
      city_id: 0,
      mobile: "09105107213",
      email: null,
      avatar_url: "https://api.digikala.com/static/files/fd4840b2.svg",
      is_legal: false,
      is_foreigner: false,
      has_password: false,
      personal_economic_number: null,
      verification_status: "verified",
      national_identity_number: "0820355410",
      gender: "male",
      birthday_iso: "1997-07-26",
      city_name: "",
      state_name: "",
      phone_hash: "a29d602c35e57bf554d0ea24ad106c66",
    },
    default_address: {
      id: 90555434,
      full_name: "محمد گل محمدی",
      address: "کمربندی قدیم، بل خاتم الانبیا، خ. فروغی، خ. فروغی 12",
      postal_code: "9461775566",
      telephone: "",
      mobile: "989105107213",
      city_id: 1881,
      state_id: 13,
      district_id: null,
      support_fmcg: false,
      is_default: true,
      latitude: 37.38756,
      longitude: 57.93571,
      building_number: "7",
      unit: "2",
      drop_off_address_id: null,
      map_image: {
        storage_ids: {
          "1": "d8d32a6cd55afed8ca66368e1f3dc5a0acb67e42_1732510003",
        },
        url: [
          "https://dkstatics-public.digikala.com/digikala-static-map-images/d8d32a6cd55afed8ca66368e1f3dc5a0acb67e42_1732510003.png",
        ],
        thumbnail_url: null,
        temporary_id: null,
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-static-map-images/d8d32a6cd55afed8ca66368e1f3dc5a0acb67e42_1732510003.png?x-oss-process=image/format,webp",
        ],
      },
      is_usable: true,
      is_general_location_jet_eligible: false,
    },
    data_layer: {
      event: "user_attribute",
      data: {
        is_logged_in: true,
        user_id: 73559674,
        is_club_user: true,
        club_points: 11,
        rfm_category: "Promising",
        total_delivered_orders: 2,
        aov: 20473750,
        magnet_membership: false,
        plus_membership: false,
        plus_membership_duration: 0,
      },
    },
    show_location_modal: false,
    modules: [],
    date_time: "2024-12-27 17:20:36",
    social_profile: {
      is_activated: false,
    },
    promotion_top_banner: [],
    cart: {
      id: 346835225,
      items_count: 3,
      payable_price: 992895000,
      digiclub: {
        points: 150,
      },
      voucher_code: null,
      cash_back: {
        amount: 0,
        digiplus_amount: 0,
        return_days: 7,
      },
      temporary_plus_subscription: [],
      delivery_package_box: [],
      bnpl_active: false,
      rrp_price: 992895000,
      shipping_cost: 0,
      voucher_discount: 0,
      shipping_cost_discount: 0,
      items_discount: 0,
      total_discount: 0,
      insurance: {
        amount: 0,
        discount: 0,
      },
      plus: [],
      delivery_package: {
        amount: 0,
        discount: 0,
      },
    },
    cart_items: [
      {
        id: 3543712920,
        cart_id: 346835225,
        quantity: 1,
        price: {
          price: 4780000,
          discount: 0,
          is_incredible: false,
          is_promotion: false,
          is_lightening_deal: false,
          is_digiplus_promotion: false,
        },
        product: {
          id: 11346825,
          title_fa: "محافظ ولتاژ ولتن مدل PS3",
          title_en: "",
          url: {
            base: null,
            uri: "/product/dkp-11346825/محافظ-ولتاژ-ولتن-مدل-ps3",
          },
          status: "marketable",
          has_quick_view: false,
          data_layer: {
            brand: "متفرقه",
            category: "[TL,نور و روشنایی]",
            metric6: 15,
            dimension2: 0,
            dimension6: 0,
            dimension7: "none",
            dimension9: 4.4,
            dimension11: 0,
            dimension20: "marketable",
            item_category2: "لوازم خانگی برقی",
            item_category3: "صوتی و تصویری",
            item_category4: "لوازم جانبی صوتی و تصویری",
            item_category5: "چندراهی برق و محافظ ولتاژ",
          },
          product_type: "product",
          test_title_fa: "",
          test_title_en: "",
          digiplus: {
            services: [
              "۴ ارسال رایگان عادی",
              "۲ ارسال سوپرمارکت",
              "پشتیبانی اختصاصی",
            ],
            services_summary: ["ارسال رایگان"],
            is_jet_eligible: false,
            cash_back: 0,
            is_general_location_jet_eligible: false,
            fast_shipping_text: null,
          },
          images: {
            main: {
              storage_ids: [],
              url: [
                "https://dkstatics-public.digikala.com/digikala-products/0a96c0bfe784287534c87aedac7853cd77593319_1684138826.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
              ],
              thumbnail_url: null,
              temporary_id: null,
              webp_url: [
                "https://dkstatics-public.digikala.com/digikala-products/0a96c0bfe784287534c87aedac7853cd77593319_1684138826.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
              ],
            },
          },
          properties: {
            is_fast_shipping: false,
            is_ship_by_seller: false,
            free_shipping_badge: false,
            is_multi_warehouse: false,
            is_fake: false,
            has_gift: false,
            min_price_in_last_month: 4769800,
            is_non_inventory: false,
            is_ad: false,
            ad: [],
            is_jet_eligible: false,
            is_medical_supplement: false,
          },
          badges: [],
          rating: {
            rate: 88,
            count: 15,
          },
          default_variant_id: 56535389,
          product_badges: [
            {
              id: 114,
              type: "simple",
              slot: "pdp_above_add_to_cart",
              priority: 5,
              payload: {
                icon: null,
                svg_icon:
                  "https://dkstatics-public.digikala.com/digikala-static/fbd708bb590bcc4dbab734bc4f9e5cf193d95c49_1716833809.svg",
                text: "200+ نفر به این کالا علاقه دارند",
                text_color: "#E7133D",
              },
            },
            {
              id: 107,
              type: "simple",
              slot: "pdp_above_add_to_cart",
              priority: 4,
              payload: {
                icon: null,
                svg_icon:
                  "https://dkstatics-public.digikala.com/digikala-static/ea3dbbaec3e7c802f50d3d46a400a5068ef8aea0_1716833848.svg",
                text: "100+ نفر بیش از ۲ بار این کالا را خریده‌اند",
                text_color: "#E7133D",
              },
            },
          ],
        },
        product_metadata: [],
        variant: {
          id: 56535389,
          lead_time: 1,
          rank: 99.88,
          rate: 88,
          statistics: {
            totally_satisfied: {
              rate_count: 9,
              rate: 60,
            },
            satisfied: {
              rate_count: 4,
              rate: 26.67,
            },
            neutral: {
              rate_count: 1,
              rate: 6.67,
            },
            dissatisfied: {
              rate_count: 1,
              rate: 6.67,
            },
            totally_dissatisfied: {
              rate_count: 0,
              rate: 0,
            },
            total_count: 15,
            total_rate: 88,
          },
          status: "marketable",
          properties: {
            is_fast_shipping: false,
            is_ship_by_seller: false,
            is_multi_warehouse: false,
            has_similar_variants: false,
            is_rural: false,
            in_digikala_warehouse: false,
          },
          digiplus: {
            services: [
              "۴ ارسال رایگان عادی",
              "۲ ارسال سوپرمارکت",
              "پشتیبانی اختصاصی",
            ],
            services_summary: ["ارسال رایگان"],
            is_jet_eligible: false,
            cash_back: 0,
            is_general_location_jet_eligible: false,
            fast_shipping_text: null,
          },
          warranty: {
            id: 3,
            title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
            title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
          },
          color: {
            id: 2,
            title: "سفید",
            hex_code: "#FFFFFF",
          },
          seller: {
            id: 1416489,
            title: "الکترو مهربان",
            code: "FYVUU",
            url: "https://www.digikala.com/seller/FYVUU/",
            rating: {
              total_rate: 80,
              total_count: 700,
              commitment: 94.9,
              no_return: 97.8,
              on_time_shipping: 86.9,
            },
            properties: {
              is_trusted: false,
              is_official: false,
              is_roosta: false,
              is_new: false,
            },
            stars: 2.15,
            grade: {
              label: "خوب",
              color: "#b1b64d",
            },
            logo: null,
            registration_date: "10 ماه و 1 هفته",
          },
          digiclub: {
            point: 48,
          },
          price: {
            selling_price: 4780000,
            rrp_price: 4780000,
            order_limit: 10,
            is_incredible: false,
            is_promotion: false,
            is_locked_for_digiplus: false,
            bnpl_active: false,
            discount_percent: 0,
            is_plus_early_access: false,
          },
          shipment_methods: {
            description: "موجود در انبار فروشنده",
            has_lead_time: false,
            providers: [
              {
                title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
                description:
                  "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
                has_lead_time: true,
                type: "digikala",
              },
            ],
          },
          has_importer_price: false,
          manufacture_price_not_exist: false,
          has_best_price_in_last_month: false,
          buy_box_notices: [],
          variant_badges: [],
        },
        properties: {
          is_drop_off_eligible: true,
        },
        shipment_methods: {
          is_digikala: true,
          is_ship_by_seller: false,
        },
        is_switchable: false,
        gifts: [],
        has_insurance: false,
        e_gift_card_properties: [],
        warnings: [],
      },
      {
        id: 3596208863,
        cart_id: 346835225,
        quantity: 1,
        price: {
          price: 986595000,
          discount: 0,
          is_incredible: false,
          is_promotion: false,
          is_lightening_deal: false,
          is_digiplus_promotion: false,
        },
        product: {},
        product_metadata: [],
        variant: {},
        properties: {
          is_drop_off_eligible: true,
        },
        shipment_methods: {
          is_digikala: true,
          is_ship_by_seller: false,
        },
        is_switchable: false,
        gifts: [],
        has_insurance: false,
        e_gift_card_properties: [],
        warnings: [],
      },
      {
        id: 3599474293,
        cart_id: 346835225,
        quantity: 1,
        price: {
          price: 1520000,
          discount: 0,
          is_incredible: false,
          is_promotion: false,
          is_lightening_deal: false,
          is_digiplus_promotion: false,
        },
        product: {
          id: 2856082,
          title_fa: "مبدل برق هادرون مدل A10-1",
          title_en: "",
          url: {
            base: null,
            uri: "/product/dkp-2856082/مبدل-برق-هادرون-مدل-a10-1",
          },
          status: "marketable",
          has_quick_view: false,
          data_layer: {
            brand: "هادرون",
            category: "[TL,نور و روشنایی]",
            metric6: 13375,
            dimension2: 0,
            dimension6: 0,
            dimension7: "none",
            dimension9: 4.6,
            dimension11: 0,
            dimension20: "marketable",
            item_category2: "لوازم خانگی برقی",
            item_category3: "صوتی و تصویری",
            item_category4: "لوازم جانبی صوتی و تصویری",
            item_category5: "چندراهی برق و محافظ ولتاژ",
          },
          product_type: "product",
          test_title_fa: "",
          test_title_en: "",
          digiplus: {
            services: [
              "۴ ارسال رایگان عادی",
              "۲ ارسال سوپرمارکت",
              "پشتیبانی اختصاصی",
              "ارسال فوری برای شهر تهران (رایگان)",
            ],
            services_summary: ["ارسال فوری برای شهر تهران (رایگان)"],
            is_jet_eligible: true,
            cash_back: 0,
            is_general_location_jet_eligible: false,
            fast_shipping_text: "ارسال امروز",
          },
          images: {
            main: {
              storage_ids: [],
              url: [
                "https://dkstatics-public.digikala.com/digikala-products/81d984567c48c2bb5bce61b2738a073cc09e640e_1607931641.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
              ],
              thumbnail_url: null,
              temporary_id: null,
              webp_url: [
                "https://dkstatics-public.digikala.com/digikala-products/81d984567c48c2bb5bce61b2738a073cc09e640e_1607931641.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
              ],
            },
          },
          properties: {
            is_fast_shipping: false,
            is_ship_by_seller: false,
            free_shipping_badge: false,
            is_multi_warehouse: false,
            is_fake: false,
            has_gift: false,
            min_price_in_last_month: 1180000,
            is_non_inventory: false,
            is_ad: false,
            ad: [],
            is_jet_eligible: false,
            is_medical_supplement: false,
          },
          badges: [],
          rating: {
            rate: 91.91910280373831,
            count: 13375,
          },
          default_variant_id: 15421121,
          product_badges: [
            {
              id: 88,
              type: "simple",
              slot: "pdp_above_add_to_cart",
              priority: 1,
              payload: {
                icon: null,
                svg_icon:
                  "https://dkstatics-public.digikala.com/digikala-static/54419b9303246cde131fcb5b251b86f2ab4aeb71_1716833765.svg",
                text: "1000+ فروش در هفته گذشته",
                text_color: "#107E18",
              },
            },
            {
              id: 111,
              type: "simple",
              slot: "pdp_above_add_to_cart",
              priority: 4,
              payload: {
                icon: null,
                svg_icon:
                  "https://dkstatics-public.digikala.com/digikala-static/ea3dbbaec3e7c802f50d3d46a400a5068ef8aea0_1716833848.svg",
                text: "500+ نفر بیش از ۲ بار این کالا را خریده‌اند",
                text_color: "#E7133D",
              },
            },
            {
              id: 117,
              type: "simple",
              slot: "pdp_above_add_to_cart",
              priority: 5,
              payload: {
                icon: null,
                svg_icon:
                  "https://dkstatics-public.digikala.com/digikala-static/fbd708bb590bcc4dbab734bc4f9e5cf193d95c49_1716833809.svg",
                text: "500+ نفر به این کالا علاقه دارند",
                text_color: "#E7133D",
              },
            },
            {
              id: 99,
              type: "simple",
              slot: "pdp_above_add_to_cart",
              priority: 2,
              payload: {
                icon: null,
                svg_icon:
                  "https://dkstatics-public.digikala.com/digikala-static/b0d6bb54a0077253781cdce04f9e16a34edc5299_1716833794.svg",
                text: "در سبد خرید 1000+ نفر",
                text_color: "#007E94",
              },
            },
            {
              id: 103,
              type: "simple",
              slot: "pdp_above_add_to_cart",
              priority: 3,
              payload: {
                icon: null,
                svg_icon:
                  "https://dkstatics-public.digikala.com/digikala-static/0e6f8a5cd47918608fecad3cd61d3a584a32d47b_1716833780.svg",
                text: "1000+ بازدید در 24 ساعت اخیر",
                text_color: "#007E94",
              },
            },
          ],
        },
        product_metadata: [],
        variant: {
          id: 15421121,
          lead_time: 0,
          rank: 99.92,
          rate: 92,
          statistics: {
            totally_satisfied: {
              rate_count: 4486,
              rate: 68.77,
            },
            satisfied: {
              rate_count: 1644,
              rate: 25.2,
            },
            neutral: {
              rate_count: 282,
              rate: 4.32,
            },
            dissatisfied: {
              rate_count: 54,
              rate: 0.83,
            },
            totally_dissatisfied: {
              rate_count: 57,
              rate: 0.87,
            },
            total_count: 6523,
            total_rate: 92,
          },
          status: "marketable",
          properties: {
            is_fast_shipping: false,
            is_ship_by_seller: false,
            is_multi_warehouse: false,
            has_similar_variants: true,
            is_rural: false,
            in_digikala_warehouse: true,
          },
          digiplus: {
            services: [
              "۴ ارسال رایگان عادی",
              "۲ ارسال سوپرمارکت",
              "پشتیبانی اختصاصی",
              "ارسال فوری برای شهر تهران (رایگان)",
            ],
            services_summary: ["ارسال فوری برای شهر تهران (رایگان)"],
            is_jet_eligible: true,
            cash_back: 0,
            is_general_location_jet_eligible: false,
            fast_shipping_text: "ارسال امروز",
          },
          warranty: {
            id: 2782,
            title_fa: "گارانتی مادام‌العمر هادرون توان",
            title_en: "گارانتی مادام‌العمر هادرون توان",
          },
          color: {
            id: 2,
            title: "سفید",
            hex_code: "#FFFFFF",
          },
          seller: {
            id: 1,
            title: "دیجی‌کالا",
            code: "5A52N",
            url: "https://www.digikala.com/seller/5A52N/",
            rating: {
              total_rate: 0,
              total_count: 0,
              commitment: 100,
              no_return: 99.9,
              on_time_shipping: 100,
            },
            properties: {
              is_trusted: false,
              is_official: false,
              is_roosta: false,
              is_new: false,
            },
            stars: 5,
            grade: {
              label: "عالی",
              color: "#00a049",
            },
            logo: null,
            registration_date: "8 سال و 4 ماه",
          },
          digiclub: {
            point: 16,
          },
          price: {
            selling_price: 1520000,
            rrp_price: 1520000,
            order_limit: 2,
            is_incredible: false,
            is_promotion: false,
            is_locked_for_digiplus: false,
            bnpl_active: false,
            marketable_stock: 2,
            discount_percent: 0,
            is_plus_early_access: false,
          },
          shipment_methods: {
            description: "موجود در انبار دیجی‌کالا",
            has_lead_time: true,
            providers: [
              {
                title: "ارسال دیجی‌کالا",
                description:
                  "این کالا در انبار دیجی‌کالا موجود و آماده پردازش است و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
                has_lead_time: false,
                type: "digikala",
              },
              {
                title: "ارسال امروز (فعلا در شهر تهران و کرج)",
                description:
                  "اگر سفارش را قبل از ساعت ۶ عصر ثبت کنید، همان روز ارسال می‌شود. در صورت ثبت سفارش بعد از ساعت ۶ عصر، فردا ارسال خواهد شد.",
                has_lead_time: false,
                type: "jet",
              },
            ],
          },
          has_importer_price: false,
          manufacture_price_not_exist: false,
          has_best_price_in_last_month: false,
          buy_box_notices: [],
          variant_badges: [
            {
              id: -1,
              type: "simple",
              slot: "pdp_above_add_to_cart",
              priority: 0,
              payload: {
                text: "تنها 2 عدد در انبار باقی مانده",
                text_color: "#d32f2f",
                icon: null,
                svg_icon:
                  "https://dkstatics-public.digikala.com/digikala-static/54419b9303246cde131fcb5b251b86f2ab4aeb71_1716833765.svg",
              },
            },
          ],
        },
        properties: {
          is_drop_off_eligible: true,
        },
        shipment_methods: {
          is_digikala: true,
          is_ship_by_seller: false,
        },
        is_switchable: false,
        gifts: [],
        has_insurance: false,
        e_gift_card_properties: [],
        warnings: [],
      },
    ],
  },
};
